include(":webauthn4j-ctap-core")
include(":webauthn4j-ctap-authenticator")
include(":webauthn4j-ctap-client")
include(":webauthn4j-ctap-uhid")
include(":webauthn4j-ctap-uhid-sample")
include(":webauthn4j-ctap-usbip")
include(":webauthn4j-ctap-usbip-sample")
