quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false
quarkus.package.output-name=unifidokey-usbip
quarkus.banner.enabled=false
quarkus.log.console.stderr=true
quarkus.log.category."com.webauthn4j".level=DEBUG
