[versions]
asm = "9.7"
ktor = "2.3.10"
zxing = "3.5.3"
junit = "4.13.2"
kotlin = "1.9.23"
kotlinx-coroutines = "1.8.0"

androidx-core-ktx = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-biometric = "1.1.0"
androidx-lifecycle = "2.7.0"
androidx-credentials = "1.2.2"
androidx-room = "2.6.1"
androidx-navigation = "2.7.7"
androidx-legacy-support-v4 = "1.0.0"
androidx-lifecycle-extensions = "2.2.0"
androidx-preference = "1.2.1"
androidx-recyclerview = "1.3.2"

material = "1.11.0"

androidSupport = "28.0.0"

googleApiServicesAndroidpublisher = "v3-rev20240328-2.0.0"
googleAuthLibraryOauth2Http = "1.23.0"
guava = "33.1.0-jre"
junit-jupiter = "5.10.2"

ossLicensesPlugin = "0.10.6"
playServicesAuth = "21.0.0"
playServicesFido = "21.0.0"
playServicesOssLicenses = "17.0.1"
playServicesSafetynet = "18.0.1"

dagger = "2.51.1"
firebaseCrashlyticsGradle = "2.9.9"
googleServices = "4.4.1"

android-tools = "8.1.2"

webauthn4j = "321b379c5a"
jackson = "2.17.0"
bouncycastle = "1.78"
slf4j = "2.0.12"
logbackAndroid = "3.0.0"

springBoot = "2.7.17"

androidx-test = "1.5.0"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso = "3.5.1"
espresso = "3.5.1"
logbackClassic = "1.5.4"
assertj = "3.25.3"
mockito = "5.8.0"
mockito-kotlin = "5.3.1"
truth = "1.4.2"
robolectric = "4.12.1"

sonarqubeGradlePlugin = "5.0.0.4638"

asciidoctorGradleJvm = "4.0.2"
org-jetbrains-kotlin-android = "1.9.23"
agp = "8.3.2"



[libraries]
# Kotlin
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

# Android
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidx-biometric" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials"}
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy-support-v4" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle-extensions" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "androidx-navigation" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle"}
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle"}
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }

android-support-annotations = { group = "com.android.support", name = "support-annotations", version.ref = "androidSupport"}

android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-tools" }

firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }

google-api-services-androidpublisher = { module = "com.google.apis:google-api-services-androidpublisher", version.ref = "googleApiServicesAndroidpublisher" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }

material = { module = "com.google.android.material:material", version.ref = "material" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-fido = { module = "com.google.android.gms:play-services-fido", version.ref = "playServicesFido" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
play-services-safetynet = { module = "com.google.android.gms:play-services-safetynet", version.ref = "playServicesSafetynet" }

# WebAuthn4J
webauthn4j-core = { module = "com.github.webauthn4j.webauthn4j:webauthn4j-core", version.ref = "webauthn4j" }
webauthn4j-test = { module = "com.github.webauthn4j.webauthn4j:webauthn4j-test", version.ref = "webauthn4j" }

# Third-party libraries
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j"}
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson"}
jackson-dataformat-cbor = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-cbor", version.ref = "jackson"}
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson"}

bouncycastle-bcpkix-jdk15to18 = { group = "org.bouncycastle", name = "bcpkix-jdk15to18", version.ref = "bouncycastle"}
bouncycastle-bcprov-jdk15to18 = { group = "org.bouncycastle", name = "bcprov-jdk15to18", version.ref = "bouncycastle"}

# build
guava = { module = "com.google.guava:guava", version.ref = "guava" }
sonarqube-gradle-plugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqubeGradlePlugin" }
asciidoctor-gradle-jvm = { module = "org.asciidoctor:asciidoctor-gradle-jvm", version.ref = "asciidoctorGradleJvm" }

# test
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test"}
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test"}
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit"}
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso"}
truth = { group = "com.google.truth", name = "truth", version.ref = "truth"}
truth-java8-extension = { group = "com.google.truth.extensions", name = "truth-java8-extension", version.ref = "truth"}
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric"}
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation" }
oss-licenses-plugins = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
