[versions]
androidx-lifecycle = "2.6.1"

androidx-test = "1.5.0"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso = "3.5.1"
espresso = "3.5.1"
truth = "1.1.5"
robolectric = "4.11.1"
mockito-kotlin = "5.1.0"
android-support-annotations = "28.0.0"


androidSupport = "28.0.0"

springBoot = "2.7.17"

[libraries]
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidx-lifecycle"}
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle"}
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}

androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test"}
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test"}
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit"}
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso"}
truth = { group = "com.google.truth", name = "truth", version.ref = "truth"}
truth-java8-extension = { group = "com.google.truth.extensions", name = "truth-java8-extension", version.ref = "truth"}
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric"}
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
espresso = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
android-support-annotations = { group = "com.android.support", name = "support-annotations", version.ref = "android-support-annotations"}



#implementation("androidx.lifecycle:lifecycle-process")
#implementation("androidx.lifecycle:lifecycle-livedata")
#implementation("androidx.lifecycle:lifecycle-viewmodel")
#implementation("androidx.lifecycle:lifecycle-livedata-ktx")
#implementation("androidx.lifecycle:lifecycle-viewmodel-ktx")
#implementation("androidx.lifecycle:lifecycle-extensions")
