package com.webauthn4j.ctap.authenticator.transport.hybrid

import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import javax.crypto.AEADBadTagException

class HybridNoiseResponderTest {
    @Test
    fun `interoperates with Rust snow KNpsk0 P256 handshake and transport`() {
        // Generated by snow 0.10 with initiator static=01*32, ephemeral=02*32,
        // responder ephemeral=04*32, PSK=03*32, and prologue=01.
        val staticPublicKey = hex(
            "046ff03b949241ce1dadd43519e6960e0a85b41a69a05c328103aa2bce1594ca1" +
                "63c4f753a55bf01dc53f6c0b0c7eee78b40c6ff7d25a96e2282b989cef71c144a",
        )
        val initial = hex(
            "04550f471003f3df97c3df506ac797f6721fb1a1fb7b8f6f83d224498a65c88e2" +
                "4136093d7012e509a73715cbd0b00a3cc0ff4b5c01b3ffa196ab1fb327036b8e" +
                "696f48fec4a26b2623cb69ae82b978a5d",
        )
        val expectedResponse = hex(
            "0473103ec30b3ccf57daae08e93534aef144a35940cf6bbba12a0cf7cbd5d65a6" +
                "4d82c8c99e9d3c45f9245ba9b27982c9aea8ec1db94b19c44795942c0eb22aa3" +
                "27bade0414573e24273213a1ad95da70d",
        )
        val expectedOutbound = hex(
            "8889fa19027fe8bf9abb732f26cb8722c2f1ec9cf9352d7ef6006a082386f5afc" +
                "8a02a301d5d0e308d7763b01265a0b1",
        )
        val inbound = hex(
            "f3d71d81aff6f7a01d99e78537374f2b888e5c393f049d76b05748825adfb439" +
                "0bec270cda4ad84f525ca33dfe369a68",
        )
        val responder = HybridNoiseResponder(staticPublicKey, ByteArray(32) { 3 }, ByteArray(32) { 4 })

        val (response, transport) = responder.accept(initial)

        assertArrayEquals(expectedResponse, response)
        assertArrayEquals(expectedOutbound, transport.encrypt(byteArrayOf(1, 2, 3, 4)))
        assertArrayEquals(byteArrayOf(1, 2, 3, 4), transport.decrypt(inbound))
        assertThrows<IllegalStateException> { responder.accept(initial) }
    }

    @Test
    fun `rejects a forged initiator handshake tag`() {
        val staticPublicKey = hex(
            "046ff03b949241ce1dadd43519e6960e0a85b41a69a05c328103aa2bce1594ca1" +
                "63c4f753a55bf01dc53f6c0b0c7eee78b40c6ff7d25a96e2282b989cef71c144a",
        )
        val forged = hex(
            "04550f471003f3df97c3df506ac797f6721fb1a1fb7b8f6f83d224498a65c88e2" +
                "4136093d7012e509a73715cbd0b00a3cc0ff4b5c01b3ffa196ab1fb327036b8e" +
                "696f48fec4a26b2623cb69ae82b978a5d",
        )
        forged[forged.lastIndex] = (forged.last().toInt() xor 1).toByte()

        assertThrows<AEADBadTagException> {
            HybridNoiseResponder(staticPublicKey, ByteArray(32) { 3 }, ByteArray(32) { 4 }).accept(forged)
        }
    }

    private fun hex(value: String): ByteArray = value.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
