name: Bump version

on:
  workflow_dispatch:
  workflow_run:
    workflows: [release]
    types: [completed]

env:
  JAVA_VERSION: 17

jobs:
  bump-version:
    permissions:
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Bump patch version
        run: |
          ./gradlew bumpPatchVersion

      - name: Switch to snapshot
        run: |
          ./gradlew switchToSnapshot

      - name: Update versions in documents
        run: |
          ./gradlew updateVersionsInDocuments

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email  "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Bump patch version"

      - name: Push commit
        run: |
          git push
