name: Doc

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [ 17 ]
        os: [ ubuntu-20.04 ]

    steps:
      - name: Setup build env
        run: |
          sudo npm --global install surge
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --local user.email "mail@ynojima.net"
          git config --local user.name "ynojima"
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Build with Gradle
        run: |
          ./gradlew javadoc generateUserGuide
      - name: Deploy to surge
        run: |
          surge build/docs/asciidoc/html5 docs.unifidokey.com
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
