name: Release

on:
  push:
    tags:
      - '*.RELEASE'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build/Unit test with Gradle
        run: |
          echo $KEYSTORE_BASE64 | base64 -d > unifidokey-upload-key.jks
          ./gradlew build assemblePlaystoreRelease bundlePlaystoreRelease
        env:
          KEYSTORE_BASE64 : ${{ secrets.KEYSTORE_BASE64  }}
          KEYSTORE_PASS : ${{ secrets.KEYSTORE_PASS  }}
          KEY_ALIAS : ${{ secrets.KEY_ALIAS  }}
          KEY_PASS : ${{ secrets.KEY_PASS  }}

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./unifidokey-handheld/build/outputs/apk/playstore/release/unifidokey-handheld-playstore-release.apk
          asset_name: unifidokey-handheld-release.apk
          asset_content_type: application/octet-stream

      - name: Upload release bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./unifidokey-handheld/build/outputs/bundle/playstore/release/unifidokey-handheld-playstore-release.aab
          asset_name: unifidokey-handheld-release.aab
          asset_content_type: application/octet-stream

      - name: Publish App bundle to Google Play Console
        run: |
          echo $GOOGLE_SERVICE_ACCOUNT_BASE64 | base64 -d > google-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=./google-service-account.json
          ./gradlew publishAppBundle
        env:
          KEYSTORE_BASE64 : ${{ secrets.KEYSTORE_BASE64  }}
          KEYSTORE_PASS : ${{ secrets.KEYSTORE_PASS  }}
          KEY_ALIAS : ${{ secrets.KEY_ALIAS  }}
          KEY_PASS : ${{ secrets.KEY_PASS  }}
          GOOGLE_SERVICE_ACCOUNT_BASE64 : ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64  }}
